# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('location_name', models.CharField(max_length=50, verbose_name='meeting location name')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='meeting location latitude')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='meeting location longitude')),
                ('content', models.TextField(verbose_name='content')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name_plural': 'help requests',
                'verbose_name': 'help request',
            },
        ),
    ]
