# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='meeting_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 0, 50, 32, 487675, tzinfo=utc), verbose_name='meeting datetime'),
            preserve_default=False,
        ),
    ]
